In [20]:
import numpy as np
from scipy.stats.stats import pearsonr

In [37]:
output_x = [1,2,3,4,5]#2 * np.random.rand(500)

In [42]:
output_y = [3,3,3,-1,3]#3 * output_x

In [15]:
output_x[:5]

array([1.22182183, 0.54631525, 0.11543241, 0.97750654, 0.76735111])

In [16]:
output_y[:5]

array([3.6654655 , 1.63894575, 0.34629722, 2.93251961, 2.30205334])

In [25]:
pearsonr(output_x, output_y)

(0.9999999999999998, 1.3415758552508151e-08)

In [26]:
np.corrcoef(output_x, output_y)

array([[1., 1.],
       [1., 1.]])

In [38]:
def correlation_calculator(a, b):
    mean_a = sum(a)/len(a)
    mean_b = sum(b)/len(b)
    num = 0
    denom_a = 0
    denom_b = 0
    for i in range(len(a)):
        num += ((a[i] - mean_a)*(b[i] - mean_b))
        denom_a += ((a[i] - mean_a))**2
        denom_b += ((b[i] - mean_b))**2
    op = num/(denom_a * denom_b)**0.5
    return op

In [43]:
correlation_calculator(output_x, output_y)

-0.35355339059327373